### ISSUE TITLE
Hello, is this warehouse still maintained? Is there time to upgrade Expo to 40?

### ISSUE THREAD

**Issue by cppfuns** [Game-X-Coin/EOSID#4]
@conr2d

**Comment by conr2d** [comment]
@cppfuns I am sorry, but this is a prototype of our first wallet project and no more maintained. I'm not a maintainer of this, but just updated the license by the request from the other.

**Comment by cppfuns** [comment]
> @cppfuns很抱歉，但这是我们第一个钱包项目的原型，不再维护。我不是这个的维护者，而是根据另一个的请求更新了许可证。

Thank you for your reply. I am trying to upgrade. Since I contacted RN for the first time, I still insist on fixing the problem
